"""Round V F73: every curated material interval is traceable -- a committed, machine-checked source map.

The map itself is generated by ``experiments/v0_9_material_source_map.py``; these tests pin the laws it reports so a
future bottle cannot ship an untraced interval, a sourced label with no locator, or a map that drifted from the code.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

from smartchem.material_spec import EvidenceKind

_ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("v0_9_material_source_map",
                                               _ROOT / "experiments" / "v0_9_material_source_map.py")
source_map = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(source_map)

_SOURCED = {EvidenceKind.SOURCE_QUOTED, EvidenceKind.DERIVED, EvidenceKind.CLAMPED}


def test_every_curated_component_carries_an_interval_evidence_record():
    bottles = source_map.curated_bottles()
    assert len(bottles) >= 9
    for bottle in bottles:
        for comp in bottle.components:
            assert comp.evidence is not None, (bottle.material_id, comp.identity_key)


def test_every_sourced_record_names_where_it_came_from():
    """A SOURCE_QUOTED / DERIVED / CLAMPED record is a claim about a document: it must carry a locator, and every
    sourced typed input must carry its own (Wave-C2 A1 parity)."""
    for bottle in source_map.curated_bottles():
        for comp in bottle.components:
            ev = comp.evidence
            if ev.kind in _SOURCED:
                assert ev.source_locators, (bottle.material_id, comp.identity_key)
                for typed in ev.inputs:
                    if typed.kind in _SOURCED:
                        assert typed.source_locator, (bottle.material_id, comp.identity_key, typed.name)


def test_the_committed_map_matches_the_generator():
    committed = (_ROOT / "docs" / "research" / "V0_9_RC_ROUND_V_MATERIAL_SOURCE_MAP.md").read_text()
    for row in source_map.rows():
        assert f"`{row['bottle']}`" in committed
        assert f"`{row['kernel']}`" in committed
    assert f"Components: {len(source_map.rows())};" in committed
