"""TRANSFORM-PROVIDER-01: the bounded search is parameterized by a typed closed provider registry.

The genericity thesis is that SmartChem is a generic bounded SEARCH compiler parameterized by a transform algebra.
This pins the seam that makes the algebra a parameter, each guarantee non-vacuously:
  * BEHAVIOUR   -- the DEFAULT registry (capped-scission only) enumerates byte-for-byte what the direct
                   ``capped_scissions`` call it replaced did, so rerouting the whole suite through it is a no-op;
  * PROVENANCE  -- each enumerated transform is tagged with the provider (id/version/witness_kind) that made it;
  * IDENTITY    -- the registry digest moves on a provider version / set / capability-manifest change (section 4.1
                   "transform/evidence provider version"; section 8.4 "generated by transform registry <digest>");
  * PARTIALITY  -- the aggregate completeness is the AND of every provider's own, so one provider hitting its
                   budget makes the whole enumeration incomplete: provider-local partiality never fakes a complete;
  * CLOSED SET  -- a registry refuses a duplicate provider id (a set, not a multiset).
"""
import pytest

from smartchem.smiles import parse_smiles
from smartchem.structure_descent import capped_scissions
from smartchem.transform_provider import (
    CappedScissionProvider,
    DEFAULT_TRANSFORM_REGISTRY,
    EnumeratedTransform,
    TransformProvider,
    TransformProviderRegistry,
)

PARA = parse_smiles("CC(=O)Nc1ccc(O)cc1")
WATER = parse_smiles("O")


class _IncompleteStub(TransformProvider):
    """A provider that always reports its family incompletely enumerated (budget hit), producing nothing."""

    provider_id = "incomplete-stub"
    provider_version = "v1"
    witness_kind = "CAPPED_SCISSION"

    @property
    def capability_manifest(self):
        return (("family", "stub"), ("always", "incomplete"))

    def enumerate_transforms(self, reactant, reagents, *, budget):
        return (), False


class TestDefaultRegistryBehaviour:
    def test_default_registry_is_byte_identical_to_direct_capped_scissions(self):
        direct, direct_complete = capped_scissions(PARA, (WATER,), budget=20_000)
        enumerated, complete = DEFAULT_TRANSFORM_REGISTRY.enumerate(PARA, (WATER,), budget=20_000)
        assert [c.digest for c in direct] == [et.transform.digest for et in enumerated]
        assert complete == direct_complete

    def test_each_enumerated_transform_carries_its_provider_provenance(self):
        enumerated, _ = DEFAULT_TRANSFORM_REGISTRY.enumerate(PARA, (WATER,), budget=20_000)
        assert enumerated
        for et in enumerated:
            assert type(et) is EnumeratedTransform
            assert et.provider_id == "capped-scission-mediated"
            assert et.provider_version == "v1"
            assert et.witness_kind == "CAPPED_SCISSION"

    def test_an_empty_reagent_pool_enumerates_nothing_without_raising(self):
        # the boundary contract: a family that needs reagents returns ((), True), never a raise (capped_scissions
        # itself would raise on an empty reagent tuple).
        enumerated, complete = DEFAULT_TRANSFORM_REGISTRY.enumerate(PARA, (), budget=20_000)
        assert enumerated == () and complete is True


class TestRegistryDigest:
    def test_a_provider_version_bump_moves_the_digest(self):
        bumped = TransformProviderRegistry((CappedScissionProvider(provider_version="v2"),))
        assert bumped.digest != DEFAULT_TRANSFORM_REGISTRY.digest

    def test_a_capability_manifest_change_moves_the_digest(self):
        wider = TransformProviderRegistry((CappedScissionProvider(max_reactant_cuts=2),))
        assert wider.digest != DEFAULT_TRANSFORM_REGISTRY.digest

    def test_adding_a_provider_moves_the_digest(self):
        two = TransformProviderRegistry((CappedScissionProvider(), _IncompleteStub()))
        assert two.digest != DEFAULT_TRANSFORM_REGISTRY.digest

    def test_the_same_registry_has_a_stable_digest(self):
        again = TransformProviderRegistry((CappedScissionProvider(),))
        assert again.digest == DEFAULT_TRANSFORM_REGISTRY.digest


class TestPartialityNeverFakesComplete:
    def test_one_incomplete_provider_makes_the_aggregate_incomplete(self):
        # capped-scission over water is COMPLETE for paracetamol; the stub is not. The registry must report the AND.
        _, capped_complete = capped_scissions(PARA, (WATER,), budget=20_000)
        assert capped_complete is True
        registry = TransformProviderRegistry((CappedScissionProvider(), _IncompleteStub()))
        _, aggregate_complete = registry.enumerate(PARA, (WATER,), budget=20_000)
        assert aggregate_complete is False   # one provider's partiality is not masked by the other's completeness


class TestClosedSet:
    def test_a_registry_needs_at_least_one_provider(self):
        with pytest.raises(ValueError, match="at least one provider"):
            TransformProviderRegistry(())

    def test_duplicate_provider_ids_are_refused(self):
        with pytest.raises(ValueError, match="distinct"):
            TransformProviderRegistry((CappedScissionProvider(), CappedScissionProvider()))
