"""
SmartChem: a conserving sequential-history layer above quantum chemistry.

Reactions are typed morphisms whose objects carry bond topology, so conservation is
enforced at construction and inherited by sequential composites. Configurations have a
commutative multiset product; morphisms do not yet have a true parallel tensor because a
linear history cannot satisfy interchange. ``Reaction.tensor`` is a compatibility name for
an explicit left-first schedule. The separate ``open_diagram`` layer supplies typed finite
wiring presentations with total boundary gluing/disjoint union and a budgeted exact canonical
observer; it does not yet supply circuit equations, a solver, or general multiphysics semantics.
The Store comonad represents a condition-indexed query plus a focus; finite response-surface
utilities explicitly evaluate that query at requested positions. Mechanism search has a
Writer-over-List shape and appends caller-supplied energy/provenance tallies alongside route
transitions. Energy comes from a pluggable oracle whose coverage and measured accuracy are
method- and domain-dependent.

    from smartchem import Config, Molecule, Reaction, favourability
    from smartchem.oracle.pyscf_oracle import PySCFOracle

    rxn = Reaction(Config.atoms("C", "O"),
                   Config.of(Molecule.diatomic("C", "O", order=3)))
    favourability(rxn, PySCFOracle("CCSD(T)", "cbs(TZ,QZ)", tight_d=False))

``smartchem.legacy`` holds the frozen original engine. It is kept executable so the
accuracy comparison stays checkable, and it is not exported here: new work builds on
``category``, ``store``, ``pathway`` and ``thermo``.
"""

from .category import (
    Bond,
    Config,
    ConservationError,
    CompositionError,
    Molecule,
    Reaction,
    UNIT,
    bond_order_profile,
    bond_signature,
    braid,
    catalytic_cycle,
    conserves,
    identity,
    is_bond_order_conserving,
    is_catalytic,
    is_regenerated,
    is_isodesmic,
    reaction_residue,
    tensor_obj,
)
from .diagnosis import (
    Diagnosis,
    Obstruction,
    diagnose,
)
from .domain import (
    EVERYTHING,
    NOTHING,
    Domain,
    DomainContradiction,
)
from .contracts import (
    ClaimKind,
    DerivationRef,
    EvidenceStatus,
    ExecutionLane,
    InferenceKind,
    ObligationOutcome,
    ObligationResult,
    ObligationStage,
    RunStatus,
    ValidityObligation,
    canonical_digest,
)
from .ledger import (
    BindingSchema,
    COMPILED,
    COMPILED_SUBJECT_TO,
    DerivedOption,
    EXHAUSTED,
    STALLED,
    WIDENED,
    IllFoundedRank,
    LedgerContradiction,
    Session,
    Slot,
    Spec,
    TypedBinding,
    UnderivedMenu,
    reaction_slot,
    shepherd,
)
from .program import (
    Adapter,
    Approval,
    ApprovedPlan,
    Artifact,
    AssemblyEvidence,
    AssemblyHypothesis,
    AssemblySpec,
    Boundary,
    CalculationSpec,
    CalibrationSpec,
    CandidatePlan,
    Certificate,
    ClaimScope,
    Component,
    Connection,
    EquivalenceContract,
    ExecutionReport,
    Identity,
    Invariant,
    ModelPatch,
    ModelSpec,
    ObservableRequest,
    ObservableValue,
    OutputContract,
    PhysicalIR,
    Port,
    Quantity,
    ReactionResidueTransform,
    ResolvedDomainProgram,
    ResolvedProgram,
    Reservoir,
    RunJournal,
    RunRecord,
    RuntimeLimits,
    SimulationRequest,
    SimulationResult,
    SolverSpec,
    SourceProgram,
    SourceTheory,
    StructuredObservableValue,
    TargetIntent,
    Transform,
    TransportEvidence,
    TransportMap,
    approve,
    compile_reaction_energy,
    compile_session_reaction_energy,
    execute,
    record_approval,
)
from .water_wave_domain import (
    CharacteristicSample,
    FlowDirection,
    HorizonDiagnostic,
    HorizonOrientation,
    HorizonPoint,
    HorizonStatus,
    ProfilePoint,
    RegimeAssumptions,
    WaterWaveSpec,
    WaveBranch,
    WaveRegime,
    WaveTarget,
    diagnose_horizon,
)
from .water_wave import (
    ShallowWaterHorizonEngine,
    WATER_WAVE_CASUALTIES,
    WATER_WAVE_OMISSIONS,
    compile_session_water_wave_horizon,
    compile_water_wave_horizon,
    water_wave_slot,
)
from .water_wave_validation_domain import (
    BackgroundSample,
    BackgroundTolerances,
    CharacteristicInterval,
    CrossingBracket,
    DeclaredWavelengthSupport,
    FluidProperties,
    SampleDiagnostic,
    ValidationDiagnostic as WaterWaveValidationDiagnostic,
    ValidationStatus as WaterWaveValidationStatus,
    WaterWaveValidationSpec,
    diagnose_water_wave_background,
)
from .water_wave_validation import (
    WATER_WAVE_VALIDATION_CASUALTIES,
    WATER_WAVE_VALIDATION_OMISSIONS,
    FiniteSectionCompatibilityEngine,
    compile_session_water_wave_validation,
    compile_water_wave_validation,
    water_wave_validation_slot,
)
from .water_wave_continuous_domain import (
    CONTINUOUS_UNCERTAINTY_SEMANTICS,
    ContinuousBackgroundSpec,
    ContinuousDiagnostic,
    ContinuousMeshResult,
    ContinuousSample,
    ContinuousStatus,
    ContinuousUncertainty,
    FrictionLaw,
    ManufacturedFamily,
    RegularityRequirement,
    SourceLaw,
    SteadyBoundary,
    solve_continuous_background,
)
from .water_wave_continuous_verifier import continuous_diagnostic_error
from .water_wave_continuous import (
    CONTINUOUS_WATER_CASUALTIES,
    CONTINUOUS_WATER_OMISSIONS,
    ContinuousFiniteV2Comparison,
    ContinuousWaterSubject,
    ContinuousWaterWaveEngine,
    compile_session_water_wave_continuous,
    compile_water_wave_continuous,
    continuous_water_slot,
)
from .human_isotope_domain import (
    AssemblyKind,
    CalibrationEvidence,
    ConstraintInventory,
    EnvironmentalProtocol,
    EvidenceBasis,
    ExposureEvent,
    ExposureMetric,
    ExposureRoute,
    FamilyWitness,
    GranularityLevel,
    GranularitySpec,
    HazardEffect,
    HazardMechanismChoice,
    HumanIsotopeSpec,
    HumanTarget,
    IdentifiabilityDiagnostic,
    IdentifiabilityStatus,
    InternalExposureMetric,
    LivingAssemblyHypothesis,
    MedianEndpointConstraint,
    MedianEndpointKind,
    PopulationProtocol,
    RecoveryModel,
    SurvivalFamily,
    ToxicokineticLink,
    TransportInventory,
    UncertaintyInterval,
    ValidationStatus,
    diagnose_human_isotope,
)
from .human_isotope import (
    HUMAN_ISOTOPE_CASUALTIES,
    HUMAN_ISOTOPE_OMISSIONS,
    HumanIsotopeIdentifiabilityEngine,
    compile_human_isotope_identifiability,
    compile_session_human_isotope_identifiability,
    human_isotope_slot,
)
from .human_survival_domain import (
    Applicability as SyntheticSurvivalApplicability,
    DataAuthority as SyntheticSurvivalDataAuthority,
    FitProtocol as SyntheticSurvivalFitProtocol,
    FitStatus as SyntheticSurvivalFitStatus,
    GeneratorTruth as SyntheticSurvivalGeneratorTruth,
    IntervalCohortRecord,
    IntervalPrediction as SyntheticSurvivalIntervalPrediction,
    OptimizerDiagnostic as SyntheticSurvivalOptimizerDiagnostic,
    ParameterEstimate as SyntheticSurvivalParameterEstimate,
    ParameterInterval as SyntheticSurvivalParameterInterval,
    RecoveryAssessment as SyntheticSurvivalRecoveryAssessment,
    Split as SyntheticSurvivalSplit,
    SurvivalAssembly as SyntheticSurvivalAssembly,
    SurvivalCalibrationResult as SyntheticSurvivalCalibrationResult,
    SurvivalCalibrationSpec as SyntheticSurvivalCalibrationSpec,
    SurvivalDataset as SyntheticSurvivalDataset,
    SurvivalFamily as SyntheticSurvivalFamily,
    SurvivalFitInput as SyntheticSurvivalFitInput,
    SurvivalFitResult as SyntheticSurvivalFitResult,
    SyntheticDataGovernance,
    SyntheticValidationStatus as SyntheticSurvivalValidationStatus,
    TruthVisibility as SyntheticSurvivalTruthVisibility,
    fit_synthetic_survival,
    fit_synthetic_survival_model,
    assess_synthetic_survival,
    interval_event_probability,
)
from .human_survival import (
    HUMAN_SURVIVAL_CASUALTIES,
    HUMAN_SURVIVAL_OMISSIONS,
    SyntheticSurvivalRecoveryEngine,
    compile_human_survival_recovery,
    compile_session_human_survival_recovery,
    human_survival_slot,
)
from .ising_lattice_gas_domain import (
    C3_EDGES,
    C3_VERTICES,
    CompletenessInventory as IsingLatticeGasCompletenessInventory,
    ExactEquilibriumMap as IsingLatticeGasExactEquilibriumMap,
    FormalBoltzmannTerm,
    IsingLatticeGasSpec,
    MicrostateMap as IsingLatticeGasMicrostateMap,
    ParameterMap as IsingLatticeGasParameterMap,
    PartitionIdentity as IsingLatticeGasPartitionIdentity,
    StateClass as IsingLatticeGasStateClass,
    derive_exact_equilibrium_map,
)
from .ising_lattice_gas import (
    ISING_LATTICE_GAS_CASUALTIES,
    ISING_LATTICE_GAS_OMISSIONS,
    ExactC3EquilibriumEngine,
    compile_ising_lattice_gas_equilibrium,
    compile_session_ising_lattice_gas_equilibrium,
    ising_lattice_gas_slot,
)
from .open_diagram import (
    BoundaryRef as OpenBoundaryRef,
    BoundarySide as OpenBoundarySide,
    CanonicalDiagram as OpenCanonicalDiagram,
    CanonicalizationBudgetExceeded,
    ComponentKind as OpenComponentKind,
    ComponentSlot as OpenComponentSlot,
    DiagramCompositionError,
    DiagramConstructionError,
    ElementPortRef as OpenElementPortRef,
    Interface as OpenInterface,
    Junction as OpenJunction,
    OpenDiagram,
    PortKind as OpenPortKind,
    StructuralEdge as OpenStructuralEdge,
    braid as open_braid,
    canonicalize as canonicalize_open_diagram,
    identity as open_identity,
    unit_interface as open_unit_interface,
)
from .structure_ir import (
    STRUCTURE_ADAPTER_SCHEMA,
    STRUCTURE_ATTACHMENT_SCHEMA,
    STRUCTURE_IR_SCHEMA,
    StructureAdapterWitness,
    StructureAttachment,
    StructureIREdge,
    StructureIR,
    StructureObservationStatus,
    adapt_open_diagram,
    structure_braid,
    structure_identity,
)
from .circuit_model_ir import (
    CIRCUIT_MODEL_IR_SCHEMA,
    CircuitModelIR,
    CircuitModelIRError,
    observe_circuit_model_ir,
)
from .circuit import (
    BoundaryLinearRelation,
    CircuitDiagnostics,
    CircuitError,
    CircuitNumericalRefusal,
    CircuitResidualError,
    DCSolveResult,
    DCSolveSpec,
    DCVoltageDrive,
    FloatingCircuitError,
    NodeVoltage,
    PositiveResistance,
    Rational,
    ResistorBranch,
    ResistorEdgeBinding,
    ResistiveDCModel,
    SourceObservation,
    blackbox_resistive_dc,
    solve_resistive_dc,
)
from .resistive_dc import (
    RESISTIVE_DC_CASUALTIES,
    RESISTIVE_DC_OMISSIONS,
    ExactResistiveDCEngine,
    ResistiveDCAnalysis,
    ResistiveDCSubject,
    analyze_resistive_dc,
    compile_resistive_dc,
    compile_session_resistive_dc,
    resistive_dc_slot,
)
from .resistive_dc_verifier import (
    DirectCircuitDiagnostics,
    DirectVerificationDecision,
    DirectVerificationReport,
    direct_preflight as preflight_resistive_dc_directly,
    verify_resistive_dc_analysis,
)
from .rlc_ac_circuit import (
    ACCircuitError,
    ACFloatingCircuitError,
    ACNumericalRefusal,
    ACResidualError,
    ConditioningRefusal,
    LosslessSingularResonanceError,
    admittance_exact as rlc_ac_admittance_exact,
    blackbox_rlc_ac,
    solve_rlc_ac,
)
from .rlc_ac_schema import (
    ACCircuitDiagnostics as RLCACCircuitDiagnostics,
    ACSolveResult,
    ACSolveSpec,
    ACSourceObservation,
    ACVoltageDrive,
    ComplexBoundaryRelation,
    ElementKind as RLCElementKind,
    GaussianComplex,
    MNAState as RLCMNAState,
    NodePhasor,
    Phasor,
    PositiveAngularFrequency,
    PositiveCapacitance,
    PositiveInductance,
    PositiveResistance as RLCPositiveResistance,
    RLCACAnalysis,
    RLCACSubject,
    RLCBranch,
    RLCComponent,
    RLCEdgeBinding,
    RLCModel,
)
from .rlc_ac import (
    RLC_AC_CASUALTIES,
    RLC_AC_OMISSIONS,
    ExactRLCACEngine,
    analyze_rlc_ac,
    compile_rlc_ac,
    compile_session_rlc_ac,
    rlc_ac_slot,
)
from .rlc_ac_verifier import (
    DirectACDiagnostics,
    DirectACVerificationDecision,
    DirectACVerificationReport,
    direct_preflight as preflight_rlc_ac_directly,
    verify_rlc_ac_analysis,
)
from .stoichiometry import (
    MAX_WRITTEN_WEIGHT,
    Completion,
    MenuContradiction,
    StoichiometryMenu,
    Written,
    composition_matrix,
    integer_kernel_basis,
    stoichiometry_menu,
)
from .store import (
    Conditions,
    SOLVENTS,
    Store,
    argmax_position,
    argmin_position,
    grid,
    is_responsive,
    response_surface,
    survey,
)
from .pathway import (
    Mechanism,
    Pathway,
    Step,
    Tally,
    best_route,
    catalytic_cycles,
    search,
)
from .thermo import (
    bonding_energy,
    configuration_energy,
    favourability,
    is_exothermic,
    reaction_energy,
)
from .geometry import (
    GeometryError,
    RelaxResult,
    VibrationalAnalysis,
    harmonic_analysis,
    is_linear,
    relax,
    seed_bond_length,
    seed_coordinates,
)

__all__ = [
    # category -- objects, morphisms, and the conservation theorem
    "Bond",
    "Config",
    "Molecule",
    "Reaction",
    "UNIT",
    "ConservationError",
    "CompositionError",
    "braid",
    "catalytic_cycle",
    "conserves",
    "identity",
    "is_catalytic",
    "is_regenerated",
    "bond_order_profile",
    "bond_signature",
    "is_bond_order_conserving",
    "is_isodesmic",
    "reaction_residue",
    "tensor_obj",
    # stoichiometry -- the inverse of `conserves`: derive the balances, never guess them
    "Completion",
    "StoichiometryMenu",
    "MenuContradiction",
    "Written",
    "MAX_WRITTEN_WEIGHT",
    "composition_matrix",
    "integer_kernel_basis",
    "stoichiometry_menu",
    # domain -- what an oracle declares it can price, before being called
    "Domain",
    "DomainContradiction",
    "EVERYTHING",
    "NOTHING",
    # contracts -- non-aliasing inference/evidence/claim and runtime states
    "ClaimKind",
    "DerivationRef",
    "EvidenceStatus",
    "ExecutionLane",
    "InferenceKind",
    "ObligationOutcome",
    "ObligationResult",
    "ObligationStage",
    "RunStatus",
    "ValidityObligation",
    "canonical_digest",
    # diagnosis -- WHY a reaction cannot be priced, as a value rather than a None
    "Diagnosis",
    "Obstruction",
    "diagnose",
    # ledger -- free parameters, and a termination rule that measures rather than believes
    "COMPILED",
    "COMPILED_SUBJECT_TO",
    "EXHAUSTED",
    "STALLED",
    "WIDENED",
    "BindingSchema",
    "DerivedOption",
    "IllFoundedRank",
    "LedgerContradiction",
    "Session",
    "Slot",
    "Spec",
    "TypedBinding",
    "UnderivedMenu",
    "reaction_slot",
    "shepherd",
    # program -- typed source-to-certificate seam and first narrow executable vertical
    "Adapter",
    "Approval",
    "ApprovedPlan",
    "Artifact",
    "AssemblyEvidence",
    "AssemblyHypothesis",
    "AssemblySpec",
    "Boundary",
    "CalculationSpec",
    "CalibrationSpec",
    "CandidatePlan",
    "Certificate",
    "ClaimScope",
    "Component",
    "Connection",
    "EquivalenceContract",
    "ExecutionReport",
    "Identity",
    "Invariant",
    "ModelPatch",
    "ModelSpec",
    "ObservableRequest",
    "ObservableValue",
    "OutputContract",
    "PhysicalIR",
    "Port",
    "Quantity",
    "ResolvedProgram",
    "Reservoir",
    "RunJournal",
    "ReactionResidueTransform",
    "ResolvedDomainProgram",
    "RunRecord",
    "RuntimeLimits",
    "SimulationRequest",
    "SimulationResult",
    "SolverSpec",
    "SourceProgram",
    "SourceTheory",
    "StructuredObservableValue",
    "TargetIntent",
    "Transform",
    "TransportEvidence",
    "TransportMap",
    "approve",
    "compile_reaction_energy",
    "execute",
    "record_approval",
    "compile_session_reaction_energy",
    # water-wave analogue -- typed classical horizon diagnostic, never literal gravity
    "CharacteristicSample",
    "FlowDirection",
    "HorizonDiagnostic",
    "HorizonOrientation",
    "HorizonPoint",
    "HorizonStatus",
    "ProfilePoint",
    "RegimeAssumptions",
    "WaterWaveSpec",
    "WaveBranch",
    "WaveRegime",
    "WaveTarget",
    "diagnose_horizon",
    "ShallowWaterHorizonEngine",
    "WATER_WAVE_CASUALTIES",
    "WATER_WAVE_OMISSIONS",
    "compile_session_water_wave_horizon",
    "compile_water_wave_horizon",
    "water_wave_slot",
    # water-wave v2 -- manufactured finite-section compatibility, not validation
    "BackgroundSample",
    "BackgroundTolerances",
    "CharacteristicInterval",
    "CrossingBracket",
    "DeclaredWavelengthSupport",
    "FluidProperties",
    "SampleDiagnostic",
    "WaterWaveValidationDiagnostic",
    "WaterWaveValidationStatus",
    "WaterWaveValidationSpec",
    "diagnose_water_wave_background",
    "WATER_WAVE_VALIDATION_CASUALTIES",
    "WATER_WAVE_VALIDATION_OMISSIONS",
    "FiniteSectionCompatibilityEngine",
    "compile_session_water_wave_validation",
    "compile_water_wave_validation",
    "water_wave_validation_slot",
    # manufactured continuous-water rung -- finite convergence, not a continuum theorem
    "CONTINUOUS_UNCERTAINTY_SEMANTICS",
    "ContinuousBackgroundSpec",
    "ContinuousDiagnostic",
    "ContinuousMeshResult",
    "ContinuousSample",
    "ContinuousStatus",
    "ContinuousUncertainty",
    "FrictionLaw",
    "ManufacturedFamily",
    "RegularityRequirement",
    "SourceLaw",
    "SteadyBoundary",
    "solve_continuous_background",
    "continuous_diagnostic_error",
    "CONTINUOUS_WATER_CASUALTIES",
    "CONTINUOUS_WATER_OMISSIONS",
    "ContinuousFiniteV2Comparison",
    "ContinuousWaterSubject",
    "ContinuousWaterWaveEngine",
    "compile_session_water_wave_continuous",
    "compile_water_wave_continuous",
    "continuous_water_slot",
    # human-isotope proxy -- typed underidentification, never a human mortality prediction
    "AssemblyKind",
    "CalibrationEvidence",
    "ConstraintInventory",
    "EnvironmentalProtocol",
    "EvidenceBasis",
    "ExposureEvent",
    "ExposureMetric",
    "ExposureRoute",
    "FamilyWitness",
    "GranularityLevel",
    "GranularitySpec",
    "HazardEffect",
    "HazardMechanismChoice",
    "HumanIsotopeSpec",
    "HumanTarget",
    "IdentifiabilityDiagnostic",
    "IdentifiabilityStatus",
    "InternalExposureMetric",
    "LivingAssemblyHypothesis",
    "MedianEndpointConstraint",
    "MedianEndpointKind",
    "PopulationProtocol",
    "RecoveryModel",
    "SurvivalFamily",
    "ToxicokineticLink",
    "TransportInventory",
    "UncertaintyInterval",
    "ValidationStatus",
    "diagnose_human_isotope",
    "HUMAN_ISOTOPE_CASUALTIES",
    "HUMAN_ISOTOPE_OMISSIONS",
    "HumanIsotopeIdentifiabilityEngine",
    "compile_human_isotope_identifiability",
    "compile_session_human_isotope_identifiability",
    "human_isotope_slot",
    # synthetic survival recovery -- data-bound proxy, never human calibration
    "SyntheticSurvivalApplicability",
    "SyntheticSurvivalDataAuthority",
    "SyntheticSurvivalFitProtocol",
    "SyntheticSurvivalFitStatus",
    "SyntheticSurvivalGeneratorTruth",
    "IntervalCohortRecord",
    "SyntheticSurvivalIntervalPrediction",
    "SyntheticSurvivalOptimizerDiagnostic",
    "SyntheticSurvivalParameterEstimate",
    "SyntheticSurvivalParameterInterval",
    "SyntheticSurvivalRecoveryAssessment",
    "SyntheticSurvivalSplit",
    "SyntheticSurvivalAssembly",
    "SyntheticSurvivalCalibrationResult",
    "SyntheticSurvivalCalibrationSpec",
    "SyntheticSurvivalDataset",
    "SyntheticSurvivalFamily",
    "SyntheticDataGovernance",
    "SyntheticSurvivalFitInput",
    "SyntheticSurvivalFitResult",
    "SyntheticSurvivalValidationStatus",
    "SyntheticSurvivalTruthVisibility",
    "fit_synthetic_survival",
    "fit_synthetic_survival_model",
    "assess_synthetic_survival",
    "interval_event_probability",
    "HUMAN_SURVIVAL_CASUALTIES",
    "HUMAN_SURVIVAL_OMISSIONS",
    "SyntheticSurvivalRecoveryEngine",
    "compile_human_survival_recovery",
    "compile_session_human_survival_recovery",
    "human_survival_slot",
    # exact finite cross-domain map -- established algebra, distinct physical referents
    "C3_EDGES",
    "C3_VERTICES",
    "IsingLatticeGasSpec",
    "IsingLatticeGasParameterMap",
    "IsingLatticeGasMicrostateMap",
    "IsingLatticeGasStateClass",
    "FormalBoltzmannTerm",
    "IsingLatticeGasPartitionIdentity",
    "IsingLatticeGasCompletenessInventory",
    "IsingLatticeGasExactEquilibriumMap",
    "derive_exact_equilibrium_map",
    "ISING_LATTICE_GAS_CASUALTIES",
    "ISING_LATTICE_GAS_OMISSIONS",
    "ExactC3EquilibriumEngine",
    "compile_ising_lattice_gas_equilibrium",
    "compile_session_ising_lattice_gas_equilibrium",
    "ising_lattice_gas_slot",
    # finite open structure -- exact syntax/coherence only, with no circuit semantics yet
    "OpenBoundaryRef",
    "OpenBoundarySide",
    "OpenCanonicalDiagram",
    "CanonicalizationBudgetExceeded",
    "OpenComponentKind",
    "OpenComponentSlot",
    "DiagramCompositionError",
    "DiagramConstructionError",
    "OpenElementPortRef",
    "OpenInterface",
    "OpenJunction",
    "OpenDiagram",
    "OpenPortKind",
    "OpenStructuralEdge",
    "open_braid",
    "canonicalize_open_diagram",
    "open_identity",
    "open_unit_interface",
    # versioned quotient representation plus presentation-bound migration witness
    "STRUCTURE_ADAPTER_SCHEMA",
    "STRUCTURE_ATTACHMENT_SCHEMA",
    "STRUCTURE_IR_SCHEMA",
    "StructureAdapterWitness",
    "StructureAttachment",
    "StructureIREdge",
    "StructureIR",
    "StructureObservationStatus",
    "adapt_open_diagram",
    "structure_braid",
    "structure_identity",
    "CIRCUIT_MODEL_IR_SCHEMA",
    "CircuitModelIR",
    "CircuitModelIRError",
    "observe_circuit_model_ir",
    "BoundaryLinearRelation",
    "CircuitDiagnostics",
    "CircuitError",
    "CircuitNumericalRefusal",
    "CircuitResidualError",
    "DCSolveResult",
    "DCSolveSpec",
    "DCVoltageDrive",
    "FloatingCircuitError",
    "NodeVoltage",
    "PositiveResistance",
    "Rational",
    "ResistorBranch",
    "ResistorEdgeBinding",
    "ResistiveDCModel",
    "SourceObservation",
    "blackbox_resistive_dc",
    "solve_resistive_dc",
    "RESISTIVE_DC_CASUALTIES",
    "RESISTIVE_DC_OMISSIONS",
    "ExactResistiveDCEngine",
    "ResistiveDCAnalysis",
    "ResistiveDCSubject",
    "analyze_resistive_dc",
    "compile_resistive_dc",
    "compile_session_resistive_dc",
    "resistive_dc_slot",
    "DirectCircuitDiagnostics",
    "DirectVerificationDecision",
    "DirectVerificationReport",
    "preflight_resistive_dc_directly",
    "verify_resistive_dc_analysis",
    # positive-frequency passive RLC E2 -- fixed-frequency ideal mathematics only
    "ACCircuitError",
    "ACFloatingCircuitError",
    "ACNumericalRefusal",
    "ACResidualError",
    "ConditioningRefusal",
    "LosslessSingularResonanceError",
    "rlc_ac_admittance_exact",
    "blackbox_rlc_ac",
    "solve_rlc_ac",
    "RLCACCircuitDiagnostics",
    "ACSolveResult",
    "ACSolveSpec",
    "ACSourceObservation",
    "ACVoltageDrive",
    "ComplexBoundaryRelation",
    "RLCElementKind",
    "GaussianComplex",
    "RLCMNAState",
    "NodePhasor",
    "Phasor",
    "PositiveAngularFrequency",
    "PositiveCapacitance",
    "PositiveInductance",
    "RLCPositiveResistance",
    "RLCACAnalysis",
    "RLCACSubject",
    "RLCBranch",
    "RLCComponent",
    "RLCEdgeBinding",
    "RLCModel",
    "RLC_AC_CASUALTIES",
    "RLC_AC_OMISSIONS",
    "ExactRLCACEngine",
    "analyze_rlc_ac",
    "compile_rlc_ac",
    "compile_session_rlc_ac",
    "rlc_ac_slot",
    "DirectACDiagnostics",
    "DirectACVerificationDecision",
    "DirectACVerificationReport",
    "preflight_rlc_ac_directly",
    "verify_rlc_ac_analysis",
    # store -- the environment comonad and finite response-surface sampling
    "Store",
    "Conditions",
    "SOLVENTS",
    "survey",
    "response_surface",
    "is_responsive",
    "grid",
    "argmin_position",
    "argmax_position",
    # pathway -- Writer/List-style branching search (float accumulation is approximate)
    "Pathway",
    "Tally",
    "Step",
    "Mechanism",
    "search",
    "catalytic_cycles",
    "best_route",
    # thermo -- separable endpoint-energy adapter
    "configuration_energy",
    "reaction_energy",
    "bonding_energy",
    "is_exothermic",
    "favourability",
    # geometry -- candidate coordinates seeded from the bond graph
    "GeometryError",
    "RelaxResult",
    "VibrationalAnalysis",
    "seed_coordinates",
    "seed_bond_length",
    "relax",
    "harmonic_analysis",
    "is_linear",
]
