"""The transform registry (grammar) identity, shared by the search layer and the compilation-IR layer.

A "transform registry" is the set of rewrite rules a search runs -- the formula-decomposition edges, the linear
capped-scission route grammar, or the convergent-DAG grammar.  Section 8.4 lets SmartChem say "all pathways
generated by transform registry ``<digest>``" only against a concrete registry identity, and section 4.1 requires
a compilation IR's digest to change when the transform-provider version changes; both need ONE canonical registry
digest that every layer agrees on.

This module is that single source of truth.  It lives BELOW both the search engines (:mod:`smartchem.experiment.routes`,
:mod:`smartchem.decompiler`) and the IR (:mod:`smartchem.compilation_ir`) so all three import the same descriptors
without a layering cycle -- the receipts stamp the digest, and the IR folds it into its request identity.

A grammar here is imperative code (there is no enumerable rule table to hash), so its identity is a DECLARED
version token -- the same discipline as every ``schema_version`` in this codebase.  The descriptor names the
grammar, its version, and the section it is specified in; :func:`canonical_digest` turns it into the stable
identity.  LIMITATION (documented, W3): the digest changes only when a descriptor's version token is bumped -- an
operator MUST bump it when the grammar's rules change, exactly as a ``schema_version`` must be bumped on a schema
change.  A structural output change is caught downstream (it bumps the STEP/ROUTE/edge candidate schemas, which
changes candidate digests); a pure rule-set change with identical output structure needs the manual bump.
"""
from __future__ import annotations

from .contracts import canonical_digest

__all__ = ["TRANSFORM_REGISTRIES", "transform_registry_digest"]

TRANSFORM_REGISTRIES: dict[str, tuple] = {
    "formula-decomposition": (
        "transform-registry", "formula-decomposition", "v1",
        "conservation-descending element-bucket decomposition edges (section 7)",
    ),
    "capped-scission-linear": (
        "transform-registry", "capped-scission-linear", "v1",
        "valence-capped bond-scission retro-steps, linear acyclic routes (section 8)",
    ),
    "capped-scission-convergent": (
        "transform-registry", "capped-scission-convergent", "v1",
        "valence-capped bond-scission retro-steps, convergent synthesis DAGs (section 8)",
    ),
    "capped-scission-decompose": (
        "transform-registry", "capped-scission-decompose", "v1",
        "one-step valence-preserving capped scissions as structure-preserving decompile candidates "
        "(section 7.3 / IR-STRUCT-01): the structural refinement whose forgetful image is a mediated edge",
    ),
}


def transform_registry_digest(kind: str) -> str:
    """The canonical digest identifying the transform grammar that generates candidates for ``kind``.

    ``kind`` is one of :data:`TRANSFORM_REGISTRIES`' keys; an unknown kind is a programming error and refused.
    """
    try:
        descriptor = TRANSFORM_REGISTRIES[kind]
    except KeyError:
        raise ValueError(
            f"unknown transform-registry kind {kind!r}; expected one of {sorted(TRANSFORM_REGISTRIES)}"
        )
    return canonical_digest(descriptor)
